name: igre
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - anyio=2.0.2=py38h578d9bd_4
  - argon2-cffi=20.1.0=py38h25fe258_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.3=pyh44b312d_0
  - boto=2.49.0=py_0
  - boto3=1.17.17=pyhd8ed1ab_0
  - botocore=1.20.17=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bz2file=0.98=py_0
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.2.1=pyhd8ed1ab_0
  - catalogue=2.0.1=py38h578d9bd_2
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.4=py38h261ae71_0
  - chardet=3.0.4=py38h06a4308_1003
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.3.1=py38h3c74f83_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cymem=2.0.5=py38h709712a_1
  - cython=0.29.24=py38h295c915_0
  - cython-blis=0.7.4=py38h5c078b8_0
  - dataclasses=0.7=pyhb2cacf7_7
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - faiss-gpu=1.7.1=py3.8_hf4b0e32_1_cuda10.1
  - freetype=2.10.4=h5ab3b9f_0
  - google-api-core=1.25.1=pyh44b312d_0
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-cloud-core=1.5.0=pyhd3deb0d_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.2=py38h8838a9a_0
  - google-resumable-media=1.2.0=pyhd3deb0d_0
  - googleapis-common-protos=1.52.0=py38h578d9bd_1
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py38h578d9bd_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - ipykernel=5.4.3=py38h81c977d_0
  - ipython=7.20.0=py38h81c977d_2
  - ipython_genutils=0.2.0=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.0=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.0=py38h578d9bd_1
  - jupyter_server=1.2.2=py38h578d9bd_1
  - jupyterlab=3.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.1.3=pyhd8ed1ab_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libedit=3.1.20191231=h14c3975_1
  - libfaiss=1.7.1=hbf11de5_1_cuda10.1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libgomp=9.3.0=h2828fa1_18
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.3=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=1.1.1=py38h8df0ef7_2
  - mistune=0.8.4=py38h25fe258_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - murmurhash=1.0.5=py38h709712a_0
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.2=py38hff7bd54_0
  - notebook=6.2.0=py38h578d9bd_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - pandas=1.2.3=py38h51da96c_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - pathy=0.4.0=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - preshed=3.0.5=py38h709712a_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.14=pyha770c72_0
  - prompt_toolkit=3.0.14=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.7.3=py38h497a2fe_1
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h25fe258_1
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.5=pyhd8ed1ab_0
  - pyzmq=20.0.0=py38h1d1b12f_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3deb0d_0
  - s3transfer=0.3.4=pyhd8ed1ab_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py38h06a4308_0
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.15.0=py38h06a4308_0
  - smart_open=2.2.1=pyh9f0ad1d_0
  - sniffio=1.2.0=py38h578d9bd_1
  - spacy=3.0.3=py38hc10631b_0
  - spacy-legacy=3.0.1=pyhd8ed1ab_0
  - sqlite=3.33.0=h62c20be_0
  - srsly=2.4.0=py38h709712a_2
  - statsmodels=0.12.2=py38h5c078b8_0
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - thinc=8.0.1=py38hc10631b_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py38
  - tornado=6.1=py38h25fe258_0
  - traitlets=5.0.5=py_0
  - typer=0.3.2=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wasabi=0.8.2=pyh44b312d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - aiohttp==3.6.3
    - antlr4-python3-runtime==4.9.1
    - appdirs==1.4.4
    - arff==0.9
    - asgiref==3.3.1
    - astunparse==1.6.3
    - autodora==0.3.31
    - colored==1.4.2
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - deprecated==1.2.11
    - django==3.1.6
    - dnutils==0.2.16
    - docopt==0.6.2
    - efemarai==1.2.0
    - en-core-web-sm==3.0.0
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - image==1.5.33
    - iniconfig==1.1.1
    - ipywidgets==7.6.3
    - jedi==0.17.2
    - jsonpatch==1.28
    - jsonpickle==1.5.2
    - jsonpointer==2.0
    - jupyterlab-widgets==1.0.0
    - kdepy==1.0.10
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - logutils==0.3.5
    - markdown==3.3.3
    - matplotlib==3.3.3
    - mpmath==1.1.0
    - multidict==4.7.6
    - munch==2.5.0
    - networkx==2.5
    - nltk==3.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - parso==0.7.1
    - pathlib2==2.3.5
    - pebble==4.6.0
    - peewee==3.14.1
    - penman==1.1.0
    - persist-queue==0.5.1
    - pluggy==0.13.1
    - plyer==2.0.0
    - pmw==2.0.1
    - polytope==0.2.3
    - portalocker==2.2.1
    - pracmln==1.2.3
    - progress==1.5
    - protobuf==3.14.0
    - psutil==5.8.0
    - py==1.10.0
    - py-cpuinfo==8.0.0
    - pyasn1-modules==0.2.8
    - pydelphin==1.5.1
    - pymongo==3.11.3
    - pyro-api==0.1.2
    - pyro-ppl==1.5.1
    - pysmt==0.9.0
    - pytest==6.2.4
    - python-engineio==3.14.2
    - python-graphviz==0.16
    - python-socketio==4.6.1
    - pywmi==0.7.15
    - regex==2020.11.13
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - sacred==0.8.2
    - scikit-learn==0.24.1
    - scikit-multilearn==0.2.0
    - scipy==1.6.0
    - seaborn==0.11.1
    - smmap==4.0.0
    - spacy-lookups-data==1.0.0
    - sqlparse==0.4.1
    - sympy==1.7.1
    - tabulate==0.8.7
    - temporary==3.0.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.1
    - termcolor==1.1.0
    - toml==0.10.2
    - torch==1.8.0
    - torch-tb-profiler==0.2.1
    - torchfile==0.1.0
    - torchvision==0.9.0
    - tqdm==4.56.0
    - visdom==0.1.8.9
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wget==3.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yarl==1.5.1
prefix: /home/rimvydas/miniconda3/envs/igre
